[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F411CEUx"
# runner = ".cargo/flash.sh"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "debug"
